version: 2

before:
  hooks:
    - rustup default stable
    - cargo fetch --locked
    - cargo install --locked cargo-zigbuild

builds:
  - builder: rust
    binary: rust-playground
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    flags:
      - --release

release:
  draft: true
