version: 2
project_name: rust-playground
before:
  hooks:
    - rustup default stable
    - cargo fetch --locked
    - cargo install --locked cargo-zigbuild
builds:
  - builder: rust
    binary: bin-crate
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - x86_64-pc-windows-gnu
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    flags:
      - --release
      - --locked
      - -p=bin-crate
archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
release:
  draft: true
